name: kiss_dependencies
description: A lightweight dependency injection package for Dart that follows the KISS (Keep It Simple, Stupid) principle.
version: 1.0.1
repository: https://github.com/WAMF/kiss_dependencies

environment:
  sdk: ^3.6.0

dependencies:
  get_it: ^8.0.3


dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
  very_good_analysis: ^7.0.0
